services:
  db:
    image: postgres:16
    container_name: mkt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: mkt-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
