export const MAKEIT_ABI = [
  "error InvalidFeeSplit(uint32 liquidityProvisionFeePpm,uint32 protocolFeePpm)",
  "error InvalidRecipient()",
  "error LpNotWhitelisted(address account)",
  "error LpProvisionQuotaExceeded(address account,uint256 requestedAssets,uint256 remainingAssets)",
  "error VaultInsufficientLiquidity(uint256 requestedAssets,uint256 availableAssets)",
  "error ZeroAssets()",
  "error ZeroShares()",
  "error ETHTransferFailed()",
  "error ExternalDexNotSet()",
  "error EffectiveMarginTooSmall(uint96 grossMarginUSDC)",
  "error InsufficientEthCoverage(uint256 requestedOpenNotionalUSDC,uint256 availableNotionalUSDC)",
  "error InvalidAddress()",
  "error InsufficientFreeUsdc(uint256 requestedUSDC,uint256 availableUSDC)",
  "error InvalidMaxLeverage(uint32 maxLeverage)",
  "error InvalidExpectedPrice()",
  "error InvalidFundingAmount(uint256 amount)",
  "error InvalidPrice()",
  "error InvalidProfitTarget(uint32 profitTargetPpm,uint32 tradeLeverage)",
  "error InvalidTolerance()",
  "error InvalidTradeLeverage(uint32 tradeLeverage,uint32 maxLeverage)",
  "error InvalidWithdrawAmount(uint256 requestedAmount)",
  "error MustUseLiquidation(uint256 tradeId,uint256 closePriceE18,uint256 tpPriceE18,uint256 slPriceE18)",
  "error NoLongNotionalToOffsetShort(uint256 requestedShortNotionalUSDC,uint256 availableLongNotionalUSDC)",
  "error NoTpOrSlHit(uint256 tradeId,uint256 closePriceE18,uint256 tpPriceE18,uint256 slPriceE18)",
  "error NotTrader()",
  "error TradingFrozen()",
  "error OracleNotSet()",
  "error PriceOutOfTolerance(uint256 oraclePriceE18,uint256 expectedPriceE18,uint256 toleranceBps)",
  "error Reentrancy()",
  "error SwapDidNotRaiseEnoughUSDC(uint256 neededUSDC,uint256 raisedUSDC)",
  "error TradeNotOpen()",
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function priceOracle() view returns (address)",
  "function externalDex() view returns (address)",
  "function getOraclePriceE18() view returns (uint256)",
  "function getTrade(uint256 tradeId) view returns ((address trader,uint8 side,uint8 status,uint40 openedAt,uint32 profitTargetPpm,uint32 leverage,uint96 marginUSDC,uint128 notionalUSDC,uint256 entryPriceE18,uint256 tpPriceE18,uint256 slPriceE18))",
  "function nextTradeId() view returns (uint256)",
  "function liquidityProvisionFeePpm() view returns (uint32)",
  "function maxLeverage() view returns (uint32)",
  "function protocolFeePpm() view returns (uint32)",
  "function protocolFeeAccruedUSDC() view returns (uint256)",
  "function protocolFeeRecipient() view returns (address)",
  "function openLongNotionalUSDC() view returns (uint256)",
  "function openShortNotionalUSDC() view returns (uint256)",
  "function reservedMarginUSDC() view returns (uint256)",
  "function tradingIsFrozen() view returns (bool)",
  "function USDC() view returns (address)",
  "function WETH() view returns (address)",
  "function asset() view returns (address)",
  "function totalAssets() view returns (uint256)",
  "function availableWithdrawalAssets() view returns (uint256)",
  "function lpProvisionWhitelist(address account) view returns (bool)",
  "function lpProvisionMaxAssets(address account) view returns (uint256)",
  "function lpProvisionUsedAssets(address account) view returns (uint256)",
  "function maxDeposit(address account) view returns (uint256)",
  "function maxMint(address account) view returns (uint256)",
  "function maxWithdraw(address owner) view returns (uint256)",
  "function maxRedeem(address owner) view returns (uint256)",
  "function previewDeposit(uint256 assets) view returns (uint256)",
  "function previewMint(uint256 shares) view returns (uint256)",
  "function previewWithdraw(uint256 assets) view returns (uint256)",
  "function previewRedeem(uint256 shares) view returns (uint256)",
  "function convertToShares(uint256 assets) view returns (uint256)",
  "function convertToAssets(uint256 shares) view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function setOracle(address newOracle)",
  "function setExternalDex(address newExternalDex)",
  "function setMaxLeverage(uint32 newMaxLeverage)",
  "function setFeeSplitPpm(uint32 newLiquidityProvisionFeePpm,uint32 newProtocolFeePpm)",
  "function setProtocolFeeRecipient(address newRecipient)",
  "function configureLpProvision(address account,bool whitelisted,uint256 maxAssets)",
  "function setTradingFrozen(bool frozen)",
  "function fundETH(uint256 wethAmount18)",
  "function fundStable(uint256 usdcAmount6)",
  "function bootstrapVault(address receiver) returns (uint256 shares)",
  "function deposit(uint256 assets,address receiver) returns (uint256 shares)",
  "function mint(uint256 shares,address receiver) returns (uint256 assets)",
  "function withdraw(uint256 assets,address receiver,address owner) returns (uint256 shares)",
  "function redeem(uint256 shares,address receiver,address owner) returns (uint256 assets)",
  "function sweepProtocolFees() returns (uint256 amount)",
  "function openLongTrade(uint256 expectedPriceE18,uint256 toleranceBps,uint32 profitTargetPpm,uint32 tradeLeverage,uint96 tradeMarginUSDC) returns (uint256 tradeId)",
  "function openShortTrade(uint256 expectedPriceE18,uint256 toleranceBps,uint32 profitTargetPpm,uint32 tradeLeverage,uint96 tradeMarginUSDC) returns (uint256 tradeId)",
  "function close(uint256 tradeId)",
  "function liquidateTrade(uint256 tradeId)",
  "function ownerWithdrawETH(uint256 wethAmount18,address to)",
  "function rebalanceUsdcToEth(uint256 usdcAmount6)",
  "function transferOwnership(address newOwner)",
  "function acceptOwnership()",
  "event OracleSet(address indexed previousOracle,address indexed newOracle)",
  "event ExternalDexSet(address indexed previousExternalDex,address indexed newExternalDex)",
  "event MaxLeverageUpdated(uint32 previousMaxLeverage,uint32 newMaxLeverage)",
  "event FeeSplitUpdated(uint32 previousLiquidityProvisionFeePpm,uint32 previousProtocolFeePpm,uint32 newLiquidityProvisionFeePpm,uint32 newProtocolFeePpm)",
  "event TradingFreezeSet(bool frozen)",
  "event ProtocolFeeRecipientUpdated(address indexed previousRecipient,address indexed newRecipient)",
  "event OwnerWithdrawETH(address indexed to,uint256 ethAmount18)",
  "event PoolFundedETH(address indexed from,uint256 wethAmount18)",
  "event PoolFundedUSDC(address indexed from,uint256 usdcAmount6)",
  "event ProtocolFeesSwept(address indexed caller,address indexed recipient,uint256 usdcAmount6)",
  "event LpProvisionConfigured(address indexed account,bool whitelisted,uint256 maxAssets)",
  "event VaultBootstrap(address indexed receiver,uint256 assets,uint256 shares)",
  "event TradeOpened(uint256 indexed tradeId,address indexed trader,uint8 side,uint32 profitTargetPpm,uint256 entryPriceE18,uint256 tpPriceE18,uint256 slPriceE18,uint32 leverage,uint256 marginUSDC,uint256 notionalUSDC)",
  "event TradeClosed(uint256 indexed tradeId,address indexed trader,uint8 side,uint8 status,uint256 closePriceE18,uint32 profitTargetPpm,uint256 payoutUSDC,int256 pnlUSDC,uint256 soldWETHForProfit,uint256 boughtWETHOnSL)",
  "event ManualRebalance(uint256 usdcSpent6,uint256 wethBought18)",
  "event OwnershipTransferStarted(address indexed previousOwner,address indexed pendingOwner)",
  "event OwnershipTransferred(address indexed previousOwner,address indexed newOwner)"
];
