export const MAKEIT_ABI_V3 = [
  "error ApproveFailed()",
  "error ETHTransferFailed()",
  "error ExternalDexNotSet()",
  "error InsufficientEthCoverage()",
  "error InsufficientEthCoverage(uint256 requestedOpenNotionalUSDC,uint256 availableNotionalUSDC)",
  "error InvalidFeeBps(uint16 feeBps)",
  "error InvalidAddress()",
  "error EffectiveMarginTooSmall(uint96 grossMarginUSDC,uint16 feeBps)",
  "error InvalidExpectedPrice()",
  "error InvalidFundingAmount(uint256 amount)",
  "error InvalidPrice()",
  "error InvalidProductConfig(uint96 marginUSDC,uint32 leverage)",
  "error InvalidProfitTarget()",
  "error InvalidProfitTarget(uint16 profitTargetPct,uint32 tradeLeverage)",
  "error InvalidTolerance()",
  "error InvalidTradeLeverage(uint32 tradeLeverage,uint32 maxLeverage)",
  "error InvalidWithdrawAmount()",
  "error InvalidWithdrawAmount(uint256 requestedAmount)",
  "error MustUseLiquidation()",
  "error MustUseLiquidation(uint256 tradeId,uint256 closePriceE18,uint256 tpPriceE18,uint256 slPriceE18)",
  "error NoTpOrSlHit()",
  "error NoTpOrSlHit(uint256 tradeId,uint256 closePriceE18,uint256 tpPriceE18,uint256 slPriceE18)",
  "error NotTrader()",
  "error OpenTradesExist()",
  "error OpenTradesExist(uint256 openNotionalUSDC,uint256 openMarginUSDC)",
  "error OracleNotSet()",
  "error PriceOutOfTolerance()",
  "error PriceOutOfTolerance(uint256 oraclePriceE18,uint256 expectedPriceE18,uint256 toleranceBps)",
  "error Reentrancy()",
  "error SwapDidNotRaiseEnoughUSDC()",
  "error SwapDidNotRaiseEnoughUSDC(uint256 neededUSDC,uint256 raisedUSDC)",
  "error TradeNotOpen()",
  "error TradingFrozen()",
  "error TransferFailed()",
  "error TransferFromFailed()",
  "error Unauthorized()",
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function priceOracle() view returns (address)",
  "function externalDex() view returns (address)",
  "function getOraclePriceE18() view returns (uint256)",
  "function getTrade(uint256 tradeId) view returns ((address trader,uint8 status,uint40 openedAt,uint16 profitTargetPct,uint32 leverage,uint96 marginUSDC,uint128 notionalUSDC,uint256 entryPriceE18,uint256 tpPriceE18,uint256 slPriceE18))",
  "function nextTradeId() view returns (uint256)",
  "function marginUSDC() view returns (uint96)",
  "function feeBps() view returns (uint16)",
  "function leverage() view returns (uint32)",
  "function openNotionalUSDC() view returns (uint256)",
  "function openMarginUSDC() view returns (uint256)",
  "function tradingIsFrozen() view returns (bool)",
  "function USDC() view returns (address)",
  "function WETH() view returns (address)",
  "function setOracle(address newOracle)",
  "function setExternalDex(address newExternalDex)",
  "function setProduct(uint96 newMarginUSDC,uint32 newLeverage)",
  "function setFeeBps(uint16 newFeeBps)",
  "function setTradingFrozen(bool frozen)",
  "function fundETH(uint256 wethAmount18)",
  "function fundStable(uint256 usdcAmount6)",
  "function openTrade(uint256 expectedPriceE18,uint256 toleranceBps,uint16 profitTargetPct,uint32 tradeLeverage) returns (uint256 tradeId)",
  "function close(uint256 tradeId)",
  "function liquidateTrade(uint256 tradeId)",
  "function liquidate(uint256 tradeId)",
  "function ownerWithdrawUSDC(uint256 usdcAmount6,address to)",
  "function ownerWithdrawETH(uint256 wethAmount18,address to)",
  "function rebalanceTopUpToTargetWETH(uint256 targetWETH18) returns (uint256 usdcSpent6,uint256 wethBought18,uint256 remainingMissingWETH18)",
  "function transferOwnership(address newOwner)",
  "function acceptOwnership()",
  "event OracleSet(address indexed previousOracle,address indexed newOracle)",
  "event ExternalDexSet(address indexed previousExternalDex,address indexed newExternalDex)",
  "event ProductConfigUpdated(uint96 marginUSDC,uint32 leverage)",
  "event FeeUpdated(uint16 previousFeeBps,uint16 newFeeBps)",
  "event TradingFreezeSet(bool frozen)",
  "event OwnerWithdrawUSDC(address indexed to,uint256 usdcAmount6)",
  "event OwnerWithdrawETH(address indexed to,uint256 ethAmount18)",
  "event PoolFundedETH(address indexed from,uint256 wethAmount18)",
  "event PoolFundedUSDC(address indexed from,uint256 usdcAmount6)",
  "event TradeOpened(uint256 indexed tradeId,address indexed trader,uint16 profitTargetPct,uint256 entryPriceE18,uint256 tpPriceE18,uint256 slPriceE18,uint32 leverage,uint256 marginUSDC,uint256 notionalUSDC)",
  "event TradeClosed(uint256 indexed tradeId,address indexed trader,uint8 status,uint256 closePriceE18,uint16 profitTargetPct,uint256 payoutUSDC,int256 pnlUSDC,uint256 soldWETHForTP,uint256 boughtWETHOnSL)",
  "event PoolRebalanced(uint256 targetWETH18,uint256 usdcSpent6,uint256 wethBought18,uint256 remainingMissingWETH18)",
  "event OwnershipTransferStarted(address indexed previousOwner,address indexed pendingOwner)",
  "event OwnershipTransferred(address indexed previousOwner,address indexed newOwner)"
];

export const MAKEIT_ABI = MAKEIT_ABI_V3;
