export const SWAP_ADAPTER_ABI = [
  "error InvalidAddress()",
  "error InvalidPrice()",
  "error InvalidSlippageBps()",
  "error InvalidTokenPair()",
  "error OracleNotSet()",
  "error Unauthorized()",
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function USDC() view returns (address)",
  "function WETH() view returns (address)",
  "function pool() view returns (address)",
  "function poolFee() view returns (uint24)",
  "function swapRouter() view returns (address)",
  "function priceOracle() view returns (address)",
  "function maxSlippageBps() view returns (uint16)",
  "function setPool(address newPool)",
  "function setSwapRouter(address newRouter)",
  "function setOracle(address oracle)",
  "function setMaxSlippageBps(uint16 newMaxSlippageBps)",
  "function sellWETHForExactUSDC(uint256 usdcNeeded6,address payer,address recipient) returns (uint256 wethSold18,uint256 usdcOut6)",
  "function buyWETHWithExactUSDC(uint256 usdcIn6,address payer,address recipient) returns (uint256 usdcSpent6,uint256 wethOut18)",
  "function transferOwnership(address newOwner)",
  "function acceptOwnership()",
  "event PoolSet(address indexed previousPool,address indexed newPool,uint24 newPoolFee)",
  "event SwapRouterSet(address indexed previousRouter,address indexed newRouter)",
  "event OracleSet(address indexed previousOracle,address indexed newOracle)",
  "event MaxSlippageBpsSet(uint16 previousMaxSlippageBps,uint16 newMaxSlippageBps)",
  "event OwnershipTransferStarted(address indexed previousOwner,address indexed pendingOwner)",
  "event OwnershipTransferred(address indexed previousOwner,address indexed newOwner)"
];
